### ISSUE TITLE
Anaconda or Miniconda?

### ISSUE THREAD

**Issue by SV-Chen-Jun** [Shiyu-Sun/Hey-world#7]
Anaconda 是一个开源的Python发行版本，其包含了conda、Python等180多个科学包及其依赖项。因为包含了大量的科学包，Anaconda 的下载文件比较大（约 531 MB），如果只需要某些包，或者需要节省带宽或存储空间，也可以使用Miniconda这个较小的发行版（仅包含conda和 Python）

Cc. @fei-dou @bingjie-huang

**Comment by fei-dou** [comment]
531MB， 这么小。我来下载个完整的，分享一下

**Comment by SV-Chen-Jun** [comment]
Here is the link: 
[https://www.anaconda.com/distribution/#download-section](url)
[https://docs.conda.io/en/latest/miniconda.html](url)

**Comment by fei-dou** [comment]
Anaconda3-2019.07-Windows-x86_64.exe
已下好。谁要 ✋

**Comment by SV-Chen-Jun** [comment]
Works now.
![image](https://user-images.githubusercontent.com/28914508/65211180-5ffd4f80-dad0-11e9-9a9e-f2235c7f166c.png)

**Comment by SV-Huang-Bingjie** [comment]
你们真会玩

**Comment by SV-Chen-Jun** [comment]
Conclusion: Anaconda. Close.
